import * as Colors from '../../../assets/styles/Colors';
import { Heading1B, Heading6S } from '../../../assets/styles/Labels';
import './PrivacyPolicy.scss';
import headerLogo from "../../../assets/images/logo/header-logo.svg";
const strings = require('../../../localisation_en.json')

function PrivacyPolicy(props) {

  return (
    <>
      <div className='static-main-view grin-texture-img'>
        <div className='container-static'>
          <img src={headerLogo} className="header-logo" alt="" />
          <div className='term-condition-main'>
            <div className='tcm-text-view'>
              <Heading1B text={strings.privacyPolicy} color={Colors.black1c} fontWeight={'700'} className="font-size-64" padding={'60px 0 60px 0'} />
              <Heading6S className="tc-head6" text={'Pedlar Store Pty Ltd (ACN 655 606 250) (Pedlar) is committed to protecting your personal information.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'This Privacy Policy sets out the details relating to your data relationship with Pedlar and applies to all services and interactions with Pedlar and other related social media sites and pages.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'This Privacy Policy applies to products and services offered by us, and by using our services you agree and consent to the collection, use and disclosure of your information in connection with providing you our services.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'What we collect and how we collect it'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'The personal information we collect about you depends on the dealings you have with Pedlar. Personal Information includes information about an individual who is reasonably identifiable. You generally have the option of interacting with us anonymously or using a pseudonym, however in some instances this may prevent us from being able to provide you with products and services, for example where you place an order for products online. The types of personal information we collect and use information depending on your interaction and transactions with us, including:'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'What Information do we collect?'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'• contact name and details; • payment and transaction information including type, bank and credit card details etc; • delivery address or collection details; •username •password •gender •social media handles• your location details through your smart phone or device; • certain departments may request sensitive information such as skin type in cosmetics or size details in intimate apparel, in order to provide you with products or services; • transaction, product, services and activity details of purchases, preferences and interactions.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'How do we collect information?'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'When may collect your personal information when you: • use or visit Pedlar’s online stores, related websites, social media platforms or Apps; • make a purchase or place an order; • setup a Pedlar account; • enter a competition or complete a survey; • send us an enquiry or provide us with feedback; • participate in a promotion, competition, or survey; • join a mailing list; • post a review, rating or comment on our website or social media page.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Platform integration '} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'You may use our services in conjunction with a related third-party service. For example, in signing up as user, you may authorise us to connect with a third-party service such as Instagram or blog platform (for influencers) or other management service (for buyers). In doing so, you authorise us to access Personal Information that may have been collected by those third-party services, and to use it in accordance with this Privacy Policy. Those third-party services will have their own policies around the collection of information and you should make yourself aware of their terms.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Use of Cookies'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Information is automatically collected through your use of the our sites, Affiliates’ websites and Apps, electronic communications, through cookies. Cookies are small text files that websites or Apps may place on your computer or device. Generally, cookies are used to recognise repeat users of websites and remember user preferences. We may collect this information both anonymously and in relation to user accounts. Cookies are also used to allow the website to gain statistical information about your usage behaviour and aggregate data to allow Pedlar to customise a user"s experience on their websites. The information is used and disclosed by us for purposes including statistical analysis and to assist us improving the functionality and usability of the website and related Apps. You can switch off cookies by adjusting the settings on your web browser.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Why we collect personal information'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'We collect your personal information to provide, administer, improve and personalise our products and services, and to support our business functions, including: • to provide you with products and services; • to improve our service operations to enhance your customer experience; • to manage and work with our service providers to fulfil your request for products and services such as processing transactions and payments, delivering products and services, providing refunds and discounts; • to register and service your account, including any online account with the Site and keeping your information up‐to‐date, and verifying your identity; • promoting and communicating Pedlar products and services through direct marketing, events and competitions, public relations and social media. We may also make use of third parties who use cookies to serve ads to you based on your past visits and use of our website. This allows us to notify you of products or offers which we think might be of interest to you; • to communicate with you and perform research and statistical analysis, such as customer satisfaction and product and service improvement purposes, tailor products and promotional offers to you, usage behaviour and user experience for online and digital platforms to improve functionality and usability. This may include matching information we collect against other information held by third parties, partners and sellers that you have consented to share your information with (We may also use and disclose de-identified data for these purposes); • to respond to your query, feedback or concerns; • responding to and interacting with regulatory bodies and relevant government agencies; • general planning and administration, and as other required or permitted by law. We may also collect, hold, use and disclose personal information for other purposes explained at the time of collection or which are required or authorised by or under law, and for which you have provided consent.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Digital marketing, advertising and opting out'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'By providing your address, email address and contact number to Pedlar or its related parties and partners, you consent to us contacting you. We may send this information in a variety of ways, including by mail, email, social media, SMS, MMS, telephone and via Pedlar Apps. You may prefer to provide to us your personal email address or mobile number rather than, for example, an email address accessible by your work colleagues. If we send you direct marketing or send you electronic marketing messages based on your consent or as otherwise permitted by applicable law, you may, at any time, withdraw your consent or opt-out by: • Contacting our Customer Service team here: hello@pedlar.store; or • Using the unsubscribe facility that we include in our electronic messages (eg email, SMS or MMS) to opt out of receiving those messages.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Sharing your personal information'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'We work with a number of suppliers that provide us with services to fulfil your request or carry out specific functions on our behalf, including: • Contracted or approved third party service providers or contractors to provide you with products or services requested by you or may be of interest to you, to process your payment, to communicate offers and promotions to you, and for product development and product, service and market research. • Our loyalty program partners, suppliers and service providers. • Approved technology services including application and systems, cloud computing facilities, development and technical support, processing, storing, hosting, research and to analyse data. • Business advisors, including lawyers, accountants, insurance, recruitment advisors and agencies, auditors or other professional service providers to the extent reasonably required. • Regulatory, investigative or government bodies to comply with applicable laws or respond to valid legal process such as a search warrant, a court order or a subpoena and fraud management.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'Some of our trusted service providers such as technology or data storage providers may be located outside of Australia including Japan, Singapore, India, Hong Kong, the Philippines, the United States of America and other countries or jurisdictions depending on the nature of the services those recipients provide to Pedlar Pty Ltd.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Protection of personal information'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Personal information we hold will be in electronic form with our trusted service provider. Any trusted service provider must observe and meet our information security requirements to minimise the risk of unauthorised access to, and loss, misuse or unapproved alteration of, personal information.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'In addition we have a number of security controls in place and use a range of resources, process and technology controls to protect your personal information. While we endeavour to protect the personal information of users of our website, we cannot guarantee the security of information you disclose online. You disclose that information at your own risk. You should be aware that no method of transmission over the Internet or method of electronic storage is 100% secure. You can also help protect your personal information by keeping your Pedlar account details confidential, access is limited and we encourage you to use a unique and strong password, limit access to your computer and log out after use. If you become aware of unauthorised access, please contact the Pedlar Customer service team as soon as practicable using these details: hello@pedlar.store '} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Third party sites'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'We may display advertisements from third parties and other content that links to third-party websites. Links to third party sites that are not operated or controlled by us are provided for your convenience. If you click on a third-party advertisement or link, you are leaving Pedlar and any personal information you provide will not be covered by this Policy. We are not responsible for the privacy or security practices of those sites. Third party websites should have their own privacy and security policies, which we encourage you to read before supplying any personal information to them.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Access and Corrections'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Access If you would like access to personal information we hold about you, please contact the Pedlar Customer Service team. When making an access request, please provide as much detail as you can about the particular information you seek, in order to help us retrieve the information. We may ask you to verify your identity before proceeding with any request you make, this includes providing us satisfactory proof of identity as determined by us.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'Corrections If you ask us to correct personal information that we hold about you, or if we are satisfied that the personal information we hold is inaccurate, out of date, incomplete, irrelevant or misleading, we will take reasonable steps to correct that information to ensure that, having regard to the purpose for which it is held, the information is accurate, up-to-date, complete, relevant and not misleading. If we correct personal information about you, and we have previously disclosed that information to another agency or organisation that is subject to the Privacy Act, you may ask us to notify that other entity. If so, we will take reasonable steps to do so, unless this would be impracticable or unlawful. You should ensure that all personal information submitted to us is complete, accurate, true and correct. Failure on your part to do so may result in our inability to provide you with the products and services you have requested. A record of the changes made to your personal information may be noted in your account or filing.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Complaints or Questions'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'If you would like further information about how we manage your personal information, or if you have any queries relating to our Privacy Policy, or wish to lodge a complaint in relation to an alleged breach of the Privacy Act, please contact the Customer Service team using the following contact details: hello@pedlar.store'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'We may ask you to submit your complaint in writing. We may discuss and share your complaint with our staff and our service providers and others as required and appropriate.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />
              <Heading6S className="tc-head6" text={'All complaints received by the Customer Service Team will be dealt with in a timely manner considering all the circumstances of the complaint. In most cases, we expect that complaints will be investigated and a response generally provided within 30 days of receipt of the complaint.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'Updates to this Policy'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'We may amend this Privacy Policy from time to time without notice. You should check this page regularly to take notice of any changes. The current version will be posted on our website and a copy may be obtained by contacting our Customer Service team.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'General'} color={Colors.black1c} fontWeight={'600'} padding={'0px 0 20px 0'} />

              <Heading6S className="tc-head6" text={'This Privacy Policy and your use of our services including the website is governed in all respects by the laws of New South Wales, Australia and you agree to submit to the exclusive jurisdiction of the courts of Australia. For information about privacy generally, you may visit the Office of the Australian Information Commissioner’s website at www.oaic.gov.au.'} color={Colors.black1c} fontWeight={'400'} padding={'0px 0 100px 0'} />
            </div>
          </div>
        </div>

      </div>
    </>
  )
}

export default PrivacyPolicy;
